import type { Metadata } from "next";
import { Poppins, Playfair_Display, Trochut } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: "400",
  subsets: ["latin"],
});
const trochut = Trochut({
  variable: "--trochut-font",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hearth",
  description: "Generated by create next app",
};

import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,
  SignOutButton,
} from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";
import { ModalProvider } from "@/components/providers/modal-provider";
import { useEffect } from "react";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    >
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={`${cn("bg-black dark:bg-dark")} antialiased`}>
          <ClerkLoading>
            {/* Optional loading UI */}
            <div className="grid justify-center h-full items-center bg-black">
              <div className="loader text-white!"></div>
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="hearth-theme"
            >
              <ModalProvider />
              {children}
            </ThemeProvider>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
